services:
  backend:
    image: "backend"
    build: ./backend
    container_name: backend
    ports:
      - "80:80"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./env/backend.env
      - ./env/config.env
    logging:
      driver: "json-file"
      options:
        max-file: "3" # number of files or file count
        max-size: "5m" # file size

  frontend:
    image: "react-vite-ts:v1.0.1"
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    env_file:
      - ./env/frontend.env
    depends_on:
      - backend
    logging:
      driver: "json-file"
      options:
        max-file: "3" # number of files or file count
        max-size: "5m" # file size


  # mongodb:
  #   image: 'mongo'
  #   volumes:
  #     - data:/data/db
  #   # environment:
  #   #   MONGO_INITDB_ROOT_USERNAME: max
  #   #   MONGO_INITDB_ROOT_PASSWORD: secret
  #     # - MONGO_INITDB_ROOT_USERNAME=max
  #   env_file:
  #     - ./env/mongo.env
  # backend:
  #   image: 'backend'
  #   #build: ./backend
  #   # build:
  #   #   context: ./backend
  #   #   dockerfile: Dockerfile
  #   #   args:
  #   #     some-arg: 1
  #   ports:
  #     - '80:80'
  #   volumes:
  #     - logs:/app/logs
  #     - ./backend:/app
  #     - /app/node_modules
  #   env_file:
  #     - ./env/backend.env
  #   depends_on:
  #     - mongodb
  #     depends_on:
#       - backend0

# volumes:
#   data:
#   logs:
